[deck]
bag="η τζάντα"
bubble="η μπουρμπουλήθρα"
"hug(n)"="η αγκαλιά"
moon="το φεγγάρι"
hour="η ώρα"
minute="το λεπτό"
second="το δευτερόλεπτο"
day="η μέρα"
week="η εβδομάδα"
month="ο μήνας"
year="ο χρόνος"
Monday="η Δεθτέρα"
Tuesday="η Τρίτη"
Wednesday="η Τετάρτη"
Thursday="η Πέμπτη"
Friday="η Παρασκευή"
Saturday="το Σάββατο"
Sunday="η Κυριακή"
weekend="το Σαββατοκύριακο"
morning="το πρωί"
midday="το μεσημέρι"
afternoon="το απόγευμα"
"night(ν)"="η νύχτα"
"night(β)"="το βράδυ"
pronounciation="προφορά"
"How do we say ... in Greek?"="Πος λένε ... στα ελληνικά;"
"What is this called in Greek?"="Πώς λέγεται αυτό στα ελληνικά;"
"Can you translate that for me?"="Μπορείς να μου το μεταφράσεις αυτό στα ελληνικά;"
