[deck]
bag="η τζάντα"
bubble="η μπουρμπουλήθρα"
"hug(noun)"="η αγκαλιά"
moon="το φεγγάρι"
hour="η ώρα"
minute="το λεπτό"
second="το δευτερόλεπτο"
day="η μέρα"
week="η εβδομάδα"
month="ο μήνας"
year="ο χρόνος"
Monday="η Δεθτέρα"
Tuesday="η Τρίτη"
Wednesday="η Τετάρτη"
Thursday="η Πέμπτη"
Friday="η Παρασκευή"
Saturday="το Σάββατο"
Sunday="η Κυριακή"
weekend="το Σαββατοκύριακο"
morning="το πρωί"
midday="το μεσημέρι"
afternoon="το απόγευμα"
"night(ν)"="η νύχτα"
"night(β)"="το βράδυ"
pronounciation="προφορά"
"How do we say ... in Greek?"="Πος λένε ... στα ελληνικά;"
"What is this called in Greek?"="Πώς λέγεται αυτό στα ελληνικά;"
"Can you translate that for me?"="Μπορείς να μου το μεταφράσεις αυτό στα ελληνικά;"
cash="μετρητά"
green="το πράσινο"
yellow="το κίτρινο"
grey="το γκρί"
purple="το μώβ"
pink="το ροζ"
brown="το καφέ"
strawberry="η φράουλα"
pineapple="ο ανανάς"
apple="το μήλο"
banana="η μπανάνα"
mandarin="το μανταρίνι"
pear="το αχλάδι"
melon="το πεπόνι"
cherry="το κεράσι"
grapes="το σταφύλι"
pomegranate="το ρόδι"
vegetable="το λαχανικό"
fruit="το φρούτο"
corn="το καλαμπόκι"
lettuce="το μαρούλι"
cucumber="το αγγούρι"
pepper="η πεπεριά"
olives="οι ελιές"
carrot="το καρότο"
zucchini="το κολοκύθι"
price="η τιμή"
offer="η προσφορά"
"produce shop"="ο μανάβης/το μανάβικο"
